### PR TITLE
Add a SAN to the DHIS certificates to avoid LE rate-limiting and make certificates identifiable.

### PR DESCRIPTION
**Pull request by R-VdP**
Add an additional SAN to the certificate to distinguish certificates requested by different servers.

Doing so avoids us running into the [rate limits][le_rate_limits] set by Let's Encrypt.
Currently, Let's Encrypt imposes a maximum of 5 identical certificates per week, including renewals. Since we reuse the same domain name for all DHIS2 deployments on the field, these all count as identical certificates, meaning that we cannot request/renew more than 5 DHIS2 certificates for our field servers per week.

This PR adds an additional SAN to the certificate, which will look like
```
xxxx.certificate-requester-identifier.automatic-certificate-validation.ocb.msf.org
```
with `xxxx` being the 12-character truncated sha256 hash of the server's host name, see MSF-OCB/NixOS#145.

Because of this additional SAN, every server will request a unique certificate, which avoids the above-mentioned rate limits.

Depends on MSF-OCB/NixOS#145.

[le_rate_limits]: https://letsencrypt.org/docs/rate-limits/

### CODE REVIEW

**Comment by R-VdP** [comment]
@ianso-msf one alternative would be to use the country, to be less granular, or a project code. But these would need to be entered manually in the `.env` file.

**Comment by R-VdP** [comment]
Note to self: why not use the server's hostname?

**Review by ianso-msf — APPROVED** [review]
oke

**Review by YvesdeVoghel — APPROVED** [review]

**Review by munnavhai — CHANGES_REQUESTED** [review]
There is an error while creating the container.

ERROR: Missing mandatory value for "labels" option interpolating ['traefik.enable=true', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.entrypoints=websecure', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.rule=Host(`${FRONTEND_RULE?}.ocb.msf.org`)', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.domains[0].main=${FRONTEND_RULE?}.ocb.msf.org', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.domains[0].sans=${HOSTNAME_HASH?}-${INSTANCE_TYPE?}.certificate-requester-identifier.automatic-certificate-validation.ocb.msf.org', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.certresolver=letsencrypt_dns'] in service "web": HOSTNAME_HASH

**Comment by R-VdP** [comment]
> There is an error while creating the container.
> 
> ERROR: Missing mandatory value for "labels" option interpolating ['traefik.enable=true', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.entrypoints=websecure', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.rule=Host(`${FRONTEND_RULE?}.ocb.msf.org`)', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.domains[0].main=${FRONTEND_RULE?}.ocb.msf.org', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.domains[0].sans=${HOSTNAME_HASH?}-${INSTANCE_TYPE?}.certificate-requester-identifier.automatic-certificate-validation.ocb.msf.org', 'traefik.http.routers.dhis2_${INSTANCE_NAME?}_${INSTANCE_TYPE?}.tls.certresolver=letsencrypt_dns'] in service "web": HOSTNAME_HASH

@munnavhai that's probably because the accompanying change to nixos that introduces the variable, has not been deployed yet on the server where you tested this.

Could you update the nixos config on that server and try again?

**Review by munnavhai — APPROVED** [review]
works fine now :)

**Pull request merged**
